# Numpy Exercises

In [87]:
import numpy as np

### Given a Numpy array, write a function to compute the sum of all its elements.

In [88]:
array = np.array([1, 2, 3, 4, 5])
# Calculates the sum of all the elements in the array
print(np.sum(array))

15


### Write a NumPy program to create a 3-D array with ones on a diagonal and zeros elsewhere.

In [116]:
# creates a 3x3 identity matrix 
array = np.eye(3)
print(array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### Given a NumPy array whose underlying data is of 'int32' type. Change the data type of the given object to 'float64'.

In [117]:
array = np.array([1,2,3,4,5])
# array.dtype returns the data type of an array
print(array.dtype)
# changes data type of array to different specified data type
array = array.astype('float64')
print(array.dtype)

int64
float64


### Given 2 arrays, remove items from the one array that are present in the other array

In [118]:
array1 = np.array([1,2,3,6,7,8])
array2 = np.array([5,6,2,9,8])
# np.setdiff1d finds the set difference of 2 arrays 
# it returns array of values in array1 that are not present in array2
# this returns elements in array1 not present in array2
print(np.setdiff1d(array1,array2))
# this returns elements in array2 not present in array1
print(np.setdiff1d(array2,array1))

[1 3 7]
[5 9]


### Find common items between 2 arrays

In [119]:
array1 = np.array([1,2,3,6,7,8])
array2 = np.array([5,6,2,9,8])
# finds the intersection (shared elements) between 2 arrays
print(np.intersect1d(array1,array2))

[2 6 8]


### Replace all even numbers in array with 2

In [120]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
# if array item is even (item%2 == 0) then replace it with 2
array[array % 2 == 0] = 2
print(array)

[2 1 2 3 2 5 2 7 2 9]


### Write a NumPy program to remove every other element from a NumPy array.

In [150]:
array = np.arange(10)
print(array)
indices = np.arange(0,10,2)
print(indices)
array = np.delete(array, indices)
print(array)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]


### Given a 2D array of shape (3, 5) and a 1D array of shape (3,). Write a Numpy program that transposes the 2D array and add the 1D array to each row of the transposed array.

In [189]:
array = np.arange(15).reshape(3,5)
print(array)
transposed = np.transpose(array)
array2 = np.arange(3)
print(array2)
print(transposed + array2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[0 1 2]
[[ 0  6 12]
 [ 1  7 13]
 [ 2  8 14]
 [ 3  9 15]
 [ 4 10 16]]


### Given two Numpy arrays (matrices), write a function to compute the product of the two matrices.



In [190]:
matrix1 = np.array(([1,2],[3,4]))
matrix2 = np.array(([5,6],[7,8]))
def matrix_multiplication(matrix1, matrix2):
   # performs matrix multiplication with 2D arrays (and scalar dot product for 1D array)
   return np.dot(matrix1,matrix2)


### Given 2 arrays, find positions (indices) where the elements are the same

In [191]:
array1 = np.array([4,8,12,16,20,24])
array2 = np.array([4,2,8,16,3,24])
# np.where() selects indices of array that satisfy a boolean condition
# it returns array of indices where array1[index] == array2[index]
print(np.where(array1==array2))

(array([0, 3, 5]),)


### Given an array, extract all items between 5 and 10 (inclusive)

In [192]:
array = np.array([5,2,4,7,3,9,1,10,11])
# finds indices from array that satisfy condition 
indices = np.where((array >= 5) & (array <= 10))
print(indices)
# for every item in indices
for i in range(len(indices)):
    for j in indices:
        # find the value of array item at the index given by values of indices
        print(array[j])

(array([0, 3, 5, 7]),)
[ 5  7  9 10]


### Given a system of linear equations represented by a matrix and a constant vector, solve for the unknowns.

In [193]:
A = np.array([[3, 2], [1, 4]])
b = np.array([5, 6])
''' This is supposed to represent:
    3x + 2y = 5
    x + 4y = 6 '''  
def solve_linear_system(a, b):
    # finds solution of linear system of equations of format Ax = b
    # A is coefficient matrix and b is constant matrix
    # It solves for x and y
    return np.linalg.solve(a,b)
solve_linear_system(A,b)

array([0.8, 1.3])

### Reverse the rows of a 2D array

In [194]:
# np.arange(9) creates an array of 9 elements from 0 to 8
# np.reshape(3,3) rehsapes the array to a 3x3 matrix (3 rows and 3 columns)
array = np.arange(9).reshape(3,3)
print(array)
# this slicing method starts at the end and goes to the beginning moving backwards by 1 to reverse rows
reverse = array[::-1]
print(reverse)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


### Flatten an array of arrays into a 1D Array

In [195]:
#array = np.array(([0,1,2],[3,4,5],[6,7,8]))
arr1 = np.arange(3)
arr2 = np.arange(3, 7)
arr3 = np.arange(7, 10)
# value error raised without dtype=object
# because the rows have different lengths
# with dtype=object, it stores it as an array of arrays instead of as a 2d array
# each element is a numpy array
array = np.array([arr1,arr2,arr3],dtype=object)
# combines multiple arrays into a single array
print(np.concatenate(array))

[0 1 2 3 4 5 6 7 8 9]


### Compute matrix determinant and inverse

In [196]:
array = np.array([[1, 2], [3, 4]])
# computes determinant of matrix
det = np.linalg.det(array)
# computes inverse of matrix
inv = np.linalg.inv(array)
print("Determinant: ",det)
print("Inverse: ",inv)

Determinant:  -2.0000000000000004
Inverse:  [[-2.   1. ]
 [ 1.5 -0.5]]


### Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of shape (4,). Subtract y from each row of x using broadcasting

In [197]:
# create array with shape (3,4)
array1 = np.array(([1,2,3,4],[5,6,7,8],[9,10,11,12]))
# create array of shape (4,0)
array2 = np.array([1,2,3,4])
# performs row-wise subtraction for elements
subtracted = array1 - array2
print(subtracted)

[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


### Make the following 4x7 array  that starts with 1 and steps by 2. Note that the first element in each row is always 4 more than the last element in the previous row.
[[ 1  3  5  7  9 11 13]

 [17 19 21 23 25 27 29]

 [33 35 37 39 41 43 45]
 
 [49 51 53 55 57 59 61]]

In [198]:
# create array that starts at 1 and stops before 65 with a step of 2 (+2 to each element)
array = np.arange(1,65,2)
print(array)
# change it to a 4x8 array
array = np.reshape(array, (4,8))
print(array)
# keep all rows but only keep columns until 7 (removes last column)
array = array[: , :7]
print(array)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63]
[[ 1  3  5  7  9 11 13 15]
 [17 19 21 23 25 27 29 31]
 [33 35 37 39 41 43 45 47]
 [49 51 53 55 57 59 61 63]]
[[ 1  3  5  7  9 11 13]
 [17 19 21 23 25 27 29]
 [33 35 37 39 41 43 45]
 [49 51 53 55 57 59 61]]


### Write a NumPy program that multiplies a 3D array of shape (2, 3, 4) by a 1D array of shape (4,) using broadcasting.

In [199]:
# create array with 24 elements from 0 to 23
# make it a 2x3x4 array
# 2x3x4 = 24 
array1 = np.arange(24).reshape(2,3,4)
print(array1)
array2 = np.array([1,2,3,4])
multiplied = array1*array2
print(multiplied)


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[[ 0  2  6 12]
  [ 4 10 18 28]
  [ 8 18 30 44]]

 [[12 26 42 60]
  [16 34 54 76]
  [20 42 66 92]]]


### Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values

In [200]:
array = np.random.random((5,5))
print(array)
min = array.min()
max = array.max()
print("Min: ", min)
print("Max: ", max)

[[0.34375483 0.43340085 0.51417604 0.51151132 0.86145452]
 [0.90695853 0.09033934 0.84331345 0.41838264 0.80433895]
 [0.03441267 0.07506172 0.18876271 0.77755396 0.74048947]
 [0.30039954 0.8977037  0.72735785 0.16811574 0.24821409]
 [0.97588898 0.14038236 0.25765058 0.74737225 0.4197679 ]]
Min:  0.03441267170925455
Max:  0.9758889802938269


### Write a NumPy program (using numpy) to sum all the multiples of 3 or 5 below 100.

In [201]:
# creates array with 100 elements from 0 to 99
array = np.arange(100)
print(array)
# if array element is divisible by 3 OR 5, add to multiples array
multiples = array[(array % 3 == 0) | (array % 5 == 0)]
# find sum of all elements in multiples array
sum = np.sum(multiples)
print(sum)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
2318
